name: LINK Gallery Update

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
   runs-on: ubuntu-latest
   steps: 
     - name: Dispatch Updates of Gallery
       run: |
         curl -L \
              -X POST \
              -H 'Accept: application/vnd.github+json' \
              -H 'Authorization: Bearer ${{ secrets.PAT }}' \
              https://api.github.com/repos/lnelab/web-link/dispatches \
              -d '{"event_type":"gallery-update","client_payload":{}}'
